import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { CommitteeReport, UserProfile } from '../types';
import { logActivity } from './activityLogService';

export interface GeneratePDFOptions {
  report: CommitteeReport;
  generatedBy: string;
  totalMembers?: number;
  activeMembers?: number;
  treasuryBalance?: number;
  activeProjects?: number;
}

export async function generateOfficialMinistryPDF(options: GeneratePDFOptions): Promise<void> {
  const { report, generatedBy, totalMembers, activeMembers, treasuryBalance, activeProjects } = options;

  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'pt',
    format: 'a4'
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 40;

  // Header Deep Green Banner
  doc.setFillColor(11, 93, 59); // #0B5D3B Deep Green
  doc.rect(0, 0, pageWidth, 85, 'F');

  // Gold accent bar
  doc.setFillColor(212, 167, 44); // #D4A72C Gold
  doc.rect(0, 85, pageWidth, 6, 'F');

  // Title text
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.text('YOUTH TRANSFORMERS MINISTRY', margin, 36);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  doc.setTextColor(254, 243, 199); // light gold
  doc.text('LEADER LEO BENIE HATEGEKA • EXECUTIVE MINISTRY REPORT', margin, 54);
  doc.setFontSize(9);
  doc.setTextColor(209, 250, 229);
  doc.text(`Official Document Verification ID: YT-${Date.now().toString(36).toUpperCase()}`, margin, 70);

  // Metadata Table
  let y = 112;
  doc.setTextColor(31, 41, 55);
  doc.setFontSize(10);

  const reportTitle = report.title || `${report.department} Progress Report`;
  const submitter = report.submittedByName || report.authorName || 'Ministry Executive';

  const metaData = [
    ['REPORT TITLE:', reportTitle, 'STATUS:', (report.status || 'SUBMITTED').toUpperCase()],
    ['DEPARTMENT:', report.department || 'Executive Leadership', 'REPORTING PERIOD:', report.reportingPeriod || 'Current Term'],
    ['SUBMITTED BY:', submitter, 'GENERATED BY:', generatedBy],
    ['DATE SUBMITTED:', report.dateSubmitted || report.dateStr || new Date().toISOString().split('T')[0], 'SECURITY LEVEL:', 'Protected Ministry Record']
  ];

  autoTable(doc, {
    startY: y,
    theme: 'grid',
    head: [],
    body: metaData,
    margin: { left: margin, right: margin },
    styles: {
      fontSize: 9,
      cellPadding: 5,
      textColor: [31, 41, 55]
    },
    columnStyles: {
      0: { fontStyle: 'bold', fillColor: [248, 250, 252], cellWidth: 120 },
      1: { cellWidth: 160 },
      2: { fontStyle: 'bold', fillColor: [248, 250, 252], cellWidth: 110 },
      3: { fontStyle: 'bold', textColor: [11, 93, 59] }
    }
  });

  // Calculate start position after table
  const lastTable = (doc as any).lastAutoTable;
  y = lastTable ? lastTable.finalY + 20 : y + 90;

  // Key Metrics Card Row if available
  if (totalMembers !== undefined || treasuryBalance !== undefined) {
    doc.setFillColor(241, 245, 249);
    doc.roundedRect(margin, y, pageWidth - margin * 2, 40, 6, 6, 'F');
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.setTextColor(71, 85, 105);

    const activeM = activeMembers ?? totalMembers ?? 0;
    const balanceStr = (treasuryBalance ?? 0).toLocaleString() + ' RWF';
    const projCount = activeProjects ?? 0;

    doc.text(`Active Members: ${activeM}`, margin + 14, y + 24);
    doc.text(`Treasury Balance: ${balanceStr}`, margin + 170, y + 24);
    doc.text(`Active Projects: ${projCount}`, margin + 360, y + 24);

    y += 54;
  }

  // Core Sections
  const execSummary = report.executiveSummary || report.accomplished || 'Comprehensive departmental activities conducted in line with Youth Transformers spiritual mandate.';
  const activities = report.activitiesCompleted || report.currentWork || 'Weekly fellowships, prayer meetings, and member outreach completed successfully.';
  const challenges = report.challenges || 'No critical bottlenecks reported during this period.';
  const nextSteps = report.nextSteps || 'Proceed with planned discipleship curriculum and campus evangelism missions.';

  const sections = [
    { title: '1. Executive Summary & Overview', content: execSummary },
    { title: '2. Activities & Deliverables Completed', content: activities },
    { title: '3. Challenges & Operational Bottlenecks', content: challenges },
    { title: '4. Strategic Next Steps & Pastoral Recommendations', content: nextSteps }
  ];

  sections.forEach((sec) => {
    if (y > 720) {
      doc.addPage();
      y = 50;
    }

    // Section title container
    doc.setFillColor(236, 253, 245); // light green container
    doc.rect(margin, y, pageWidth - margin * 2, 20, 'F');
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(11, 93, 59); // deep green
    doc.text(sec.title, margin + 8, y + 14);
    y += 26;

    // Section body
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9.5);
    doc.setTextColor(55, 65, 81);

    const splitLines = doc.splitTextToSize(sec.content || 'None reported.', pageWidth - margin * 2 - 16);
    doc.text(splitLines, margin + 8, y);
    y += splitLines.length * 13 + 18;
  });

  // Verification & Signature Section
  if (y > 680) {
    doc.addPage();
    y = 50;
  }

  y += 10;
  doc.setDrawColor(203, 213, 225);
  doc.line(margin, y, pageWidth - margin, y);
  y += 30;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor(30, 41, 59);
  doc.text('VERIFIED BY DEPARTMENT COORDINATION:', margin, y);
  doc.text('APPROVED BY MINISTRY LEADER:', margin + 270, y);

  y += 35;
  doc.line(margin, y, margin + 200, y);
  doc.line(margin + 270, y, margin + 470, y);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.text(`${submitter} • Authorized Submitter`, margin, y + 12);
  doc.text('Leader Leo Benie Hategeka • Youth Transformers', margin + 270, y + 12);

  // Footer on all pages
  const totalPages = (doc.internal as any).getNumberOfPages();
  const dateNow = new Date().toLocaleString();

  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setDrawColor(226, 232, 240);
    doc.line(margin, 800, pageWidth - margin, 800);

    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 116, 139);
    doc.text(
      `Generated by ${generatedBy} on ${dateNow} • Youth Transformers Ministry Management Portal`,
      margin,
      814
    );
    doc.text(`Page ${i} of ${totalPages}`, pageWidth - margin - 50, 814);
  }

  const cleanPeriod = (report.reportingPeriod || 'report').replace(/[^a-zA-Z0-9_-]/g, '_');
  const filename = `YouthTransformers_${cleanPeriod}_Official_Report.pdf`;

  doc.save(filename);
}

export async function generateAndDownloadReportPdf(
  report: CommitteeReport,
  currentUser: UserProfile
): Promise<void> {
  return generateOfficialMinistryPDF({
    report,
    generatedBy: `${currentUser.displayName} (${currentUser.role})`
  });
}

// ================= 7 DEPARTMENT-SPECIFIC AUTHORIZED REAL PDF EXPORTERS =================

import {
  getBibleStudies,
  getFinanceTransactions,
  getFollowUpCases,
  getMembers,
  getSocialPosts,
  getProjects,
  getEquipment,
  getAttendance,
  getCommitteeTasks,
  getReports
} from './firestoreService';

function createPdfBase(title: string, subtitle: string, dept: string, verificationId: string, currentUser: UserProfile) {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'pt', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 40;

  // Header Deep Green Banner
  doc.setFillColor(11, 93, 59);
  doc.rect(0, 0, pageWidth, 85, 'F');

  // Gold accent bar
  doc.setFillColor(212, 167, 44);
  doc.rect(0, 85, pageWidth, 6, 'F');

  // Title
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.text('YOUTH TRANSFORMERS MINISTRY', margin, 36);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  doc.setTextColor(254, 243, 199);
  doc.text(subtitle.toUpperCase(), margin, 54);

  doc.setFontSize(9);
  doc.setTextColor(209, 250, 229);
  doc.text(`Official Document Verification ID: ${verificationId}`, margin, 70);

  // Meta Table
  const meta = [
    ['REPORT TITLE:', title, 'DEPARTMENT:', dept],
    ['GENERATED BY:', `${currentUser.displayName} (${currentUser.role})`, 'DATE:', new Date().toLocaleDateString()],
    ['MINISTRY LEADER:', 'Leo Benie Hategeka', 'SECURITY CLASSIFICATION:', 'Verified Official Record']
  ];

  autoTable(doc, {
    startY: 105,
    theme: 'grid',
    head: [],
    body: meta,
    margin: { left: margin, right: margin },
    styles: { fontSize: 8.5, cellPadding: 4, textColor: [31, 41, 55] },
    columnStyles: {
      0: { fontStyle: 'bold', fillColor: [248, 250, 252], cellWidth: 110 },
      1: { cellWidth: 160 },
      2: { fontStyle: 'bold', fillColor: [248, 250, 252], cellWidth: 110 },
      3: { fontStyle: 'bold', textColor: [11, 93, 59] }
    }
  });

  return { doc, pageWidth, margin };
}

function finalizeAndSavePdf(doc: jsPDF, filename: string, currentUser: UserProfile, submitterTitle: string, submitterName: string) {
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 40;
  const lastTable = (doc as any).lastAutoTable;
  let y = lastTable ? lastTable.finalY + 30 : 600;

  if (y > 700) {
    doc.addPage();
    y = 60;
  }

  // Signatures
  doc.setDrawColor(203, 213, 225);
  doc.line(margin, y, pageWidth - margin, y);
  y += 24;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8.5);
  doc.setTextColor(30, 41, 59);
  doc.text(`DEPARTMENT HEAD:`, margin, y);
  doc.text('EXECUTIVE OVERSIGHT:', margin + 270, y);

  y += 30;
  doc.line(margin, y, margin + 200, y);
  doc.line(margin + 270, y, margin + 470, y);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.text(`${submitterName} • ${submitterTitle}`, margin, y + 12);
  doc.text('Leader Leo Benie Hategeka • General Overseer', margin + 270, y + 12);

  // Footers
  const totalPages = (doc.internal as any).getNumberOfPages();
  const dateNow = new Date().toLocaleString();

  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setDrawColor(226, 232, 240);
    doc.line(margin, 800, pageWidth - margin, 800);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 116, 139);
    doc.text(`Generated by ${currentUser.displayName} on ${dateNow} • Youth Transformers Ministry Management Portal`, margin, 814);
    doc.text(`Page ${i} of ${totalPages}`, pageWidth - margin - 50, 814);
  }

  doc.save(filename);
}

// 1. BIBLE STUDY REPORT PDF
export async function downloadBibleStudyReportPDF(currentUser: UserProfile): Promise<void> {
  const isAuthorized = currentUser.role === 'bible_study' || currentUser.role === 'leader';
  if (!isAuthorized) {
    await logActivity({
      actorUid: currentUser.uid,
      actorName: currentUser.displayName,
      actorRole: currentUser.role,
      action: 'Unauthorized PDF Download Rejected',
      module: 'bible_study',
      resourceType: 'pdf',
      resourceId: 'rep_bible_study',
      details: `Denied Bible Study PDF download to ${currentUser.displayName} (${currentUser.role})`,
      result: 'denied'
    });
    throw new Error('Access Denied: You do not have permission to download Bible Study reports.');
  }

  const studies = await getBibleStudies();
  const verId = `YT-BS-${Date.now().toString(36).toUpperCase()}`;
  const { doc, margin } = createPdfBase('Official Bible Study & Doctrinal Report', 'Bible Study Department Report', 'Bible Study & Spiritual Growth', verId, currentUser);

  const tableData = studies.map(s => [
    s.dateStr,
    s.title,
    s.scriptureReferences || 'N/A',
    s.preacher || s.host || 'Ministry Leader',
    `${s.actualAttendance ?? s.expectedAttendance ?? 0} Disciples`,
    s.recurrence.toUpperCase()
  ]);

  autoTable(doc, {
    startY: (doc as any).lastAutoTable.finalY + 20,
    head: [['Date', 'Topic / Study Theme', 'Scripture Passage', 'Teacher / Exhorter', 'Attendance', 'Recurrence']],
    body: tableData,
    margin: { left: margin, right: margin },
    theme: 'striped',
    headStyles: { fillColor: [11, 93, 59], textColor: [255, 255, 255], fontStyle: 'bold', fontSize: 8 },
    styles: { fontSize: 8, cellPadding: 5 }
  });

  finalizeAndSavePdf(doc, 'YouthTransformers_BibleStudy_Report.pdf', currentUser, 'Bible Study Coordinator', 'Liona Akaliza');

  await logActivity({
    actorUid: currentUser.uid,
    actorName: currentUser.displayName,
    actorRole: currentUser.role,
    action: 'Official Department PDF Generated',
    module: 'bible_study',
    resourceType: 'pdf',
    resourceId: verId,
    details: `Generated Bible Study PDF with ${studies.length} verified sessions`,
    result: 'success'
  });
}

// 2. FINANCE REPORT PDF
export async function downloadFinanceReportPDF(currentUser: UserProfile): Promise<void> {
  const isAuthorized = currentUser.role === 'accountant' || currentUser.role === 'leader';
  if (!isAuthorized) {
    await logActivity({
      actorUid: currentUser.uid,
      actorName: currentUser.displayName,
      actorRole: currentUser.role,
      action: 'Unauthorized PDF Download Rejected',
      module: 'finance',
      resourceType: 'pdf',
      resourceId: 'rep_finance',
      details: `Denied Finance PDF download to ${currentUser.displayName} (${currentUser.role})`,
      result: 'denied'
    });
    throw new Error('Access Denied: You do not have permission to download Finance reports.');
  }

  const txs = await getFinanceTransactions();
  const income = txs.filter(t => t.type === 'income').reduce((s, t) => s + t.amount, 0);
  const expense = txs.filter(t => t.type === 'expense').reduce((s, t) => s + t.amount, 0);
  const balance = income - expense;

  const verId = `YT-FIN-${Date.now().toString(36).toUpperCase()}`;
  const { doc, margin, pageWidth } = createPdfBase('Official Financial Stewardship & Audit Report', 'Finance & Treasury Department Report', 'Finance & Treasury', verId, currentUser);

  let y = (doc as any).lastAutoTable.finalY + 15;
  doc.setFillColor(241, 245, 249);
  doc.roundedRect(margin, y, pageWidth - margin * 2, 36, 6, 6, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor(71, 85, 105);
  doc.text(`Total Inflows: ${income.toLocaleString()} RWF`, margin + 15, y + 22);
  doc.text(`Total Outflows: ${expense.toLocaleString()} RWF`, margin + 175, y + 22);
  doc.setTextColor(11, 93, 59);
  doc.text(`Net Treasury Balance: ${balance.toLocaleString()} RWF`, margin + 335, y + 22);

  const tableData = txs.map(t => [
    t.dateStr,
    t.description,
    t.category,
    t.type.toUpperCase(),
    `${t.amount.toLocaleString()} RWF`,
    t.recordedBy
  ]);

  autoTable(doc, {
    startY: y + 46,
    head: [['Date', 'Transaction Description', 'Category', 'Type', 'Amount (RWF)', 'Recorded By']],
    body: tableData,
    margin: { left: margin, right: margin },
    theme: 'striped',
    headStyles: { fillColor: [11, 93, 59], textColor: [255, 255, 255], fontStyle: 'bold', fontSize: 8 },
    styles: { fontSize: 8, cellPadding: 5 }
  });

  finalizeAndSavePdf(doc, 'YouthTransformers_Finance_Report.pdf', currentUser, 'Ministry Accountant', 'Ebenezer Mugisha');

  await logActivity({
    actorUid: currentUser.uid,
    actorName: currentUser.displayName,
    actorRole: currentUser.role,
    action: 'Official Department PDF Generated',
    module: 'finance',
    resourceType: 'pdf',
    resourceId: verId,
    details: `Generated Finance PDF with ${txs.length} verified transactions (Balance: ${balance.toLocaleString()} RWF)`,
    result: 'success'
  });
}

// 3. MEMBER CARE REPORT PDF
export async function downloadMemberCareReportPDF(currentUser: UserProfile): Promise<void> {
  const isAuthorized = currentUser.role === 'member_care' || currentUser.role === 'leader';
  if (!isAuthorized) {
    await logActivity({
      actorUid: currentUser.uid,
      actorName: currentUser.displayName,
      actorRole: currentUser.role,
      action: 'Unauthorized PDF Download Rejected',
      module: 'member_care',
      resourceType: 'pdf',
      resourceId: 'rep_member_care',
      details: `Denied Member Care PDF download to ${currentUser.displayName} (${currentUser.role})`,
      result: 'denied'
    });
    throw new Error('Access Denied: You do not have permission to download Member Care reports.');
  }

  const cases = await getFollowUpCases();
  const members = await getMembers();
  const verId = `YT-MC-${Date.now().toString(36).toUpperCase()}`;
  const { doc, margin, pageWidth } = createPdfBase('Pastoral Member Care & Welfare Report', 'Member Care Department Report', 'Pastoral Member Care', verId, currentUser);

  let y = (doc as any).lastAutoTable.finalY + 15;
  doc.setFillColor(241, 245, 249);
  doc.roundedRect(margin, y, pageWidth - margin * 2, 36, 6, 6, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor(71, 85, 105);
  doc.text(`Total Ministry Disciples: ${members.length}`, margin + 15, y + 22);
  doc.text(`Active Follow-Up Cases: ${cases.filter(c => c.status !== 'resolved').length}`, margin + 190, y + 22);
  doc.text(`Resolved Welfare Cases: ${cases.filter(c => c.status === 'resolved').length}`, margin + 355, y + 22);

  const tableData = cases.map(c => [
    c.dateOpened,
    c.memberName,
    c.reason,
    c.priority.toUpperCase(),
    c.status.replace('_', ' ').toUpperCase(),
    c.assignedToName,
    c.nextFollowUpDate || 'Pending'
  ]);

  autoTable(doc, {
    startY: y + 46,
    head: [['Date Opened', 'Disciple Name', 'Pastoral Concern', 'Priority', 'Status', 'Assigned Leader', 'Next Follow-Up']],
    body: tableData,
    margin: { left: margin, right: margin },
    theme: 'striped',
    headStyles: { fillColor: [11, 93, 59], textColor: [255, 255, 255], fontStyle: 'bold', fontSize: 8 },
    styles: { fontSize: 8, cellPadding: 5 }
  });

  finalizeAndSavePdf(doc, 'YouthTransformers_MemberCare_Report.pdf', currentUser, 'Pastoral Care Leader', 'Cedrick Gisubizo');

  await logActivity({
    actorUid: currentUser.uid,
    actorName: currentUser.displayName,
    actorRole: currentUser.role,
    action: 'Official Department PDF Generated',
    module: 'member_care',
    resourceType: 'pdf',
    resourceId: verId,
    details: `Generated Member Care PDF with ${cases.length} pastoral cases`,
    result: 'success'
  });
}

// 4. SOCIAL MEDIA REPORT PDF
export async function downloadSocialMediaReportPDF(currentUser: UserProfile): Promise<void> {
  const isAuthorized = currentUser.role === 'social_media' || currentUser.role === 'leader';
  if (!isAuthorized) {
    await logActivity({
      actorUid: currentUser.uid,
      actorName: currentUser.displayName,
      actorRole: currentUser.role,
      action: 'Unauthorized PDF Download Rejected',
      module: 'social_media',
      resourceType: 'pdf',
      resourceId: 'rep_social_media',
      details: `Denied Social Media PDF download to ${currentUser.displayName} (${currentUser.role})`,
      result: 'denied'
    });
    throw new Error('Access Denied: You do not have permission to download Social Media reports.');
  }

  const posts = await getSocialPosts();
  const totalViews = posts.reduce((sum, p) => sum + (p.views || 0), 0);
  const totalLikes = posts.reduce((sum, p) => sum + (p.likes || 0), 0);
  const verId = `YT-SM-${Date.now().toString(36).toUpperCase()}`;
  const { doc, margin, pageWidth } = createPdfBase('Digital Evangelism & Social Media Report', 'Social Media Ministry Report', 'Digital Evangelism & Social Media', verId, currentUser);

  let y = (doc as any).lastAutoTable.finalY + 15;
  doc.setFillColor(241, 245, 249);
  doc.roundedRect(margin, y, pageWidth - margin * 2, 36, 6, 6, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor(71, 85, 105);
  doc.text(`Total Published Content: ${posts.length}`, margin + 15, y + 22);
  doc.text(`Total Gospel Views/Reach: ${totalViews.toLocaleString()}`, margin + 180, y + 22);
  doc.text(`Audience Engagement/Likes: ${totalLikes.toLocaleString()}`, margin + 355, y + 22);

  const tableData = posts.map(p => [
    p.scheduledDate || p.postDate || 'N/A',
    p.platform.toUpperCase(),
    p.title,
    p.status.toUpperCase(),
    (p.views ?? 0).toLocaleString(),
    (p.likes ?? 0).toLocaleString(),
    p.responsiblePerson || 'Digital Team'
  ]);

  autoTable(doc, {
    startY: y + 46,
    head: [['Scheduled Date', 'Platform', 'Content Title / Topic', 'Status', 'Views', 'Likes', 'Author']],
    body: tableData,
    margin: { left: margin, right: margin },
    theme: 'striped',
    headStyles: { fillColor: [11, 93, 59], textColor: [255, 255, 255], fontStyle: 'bold', fontSize: 8 },
    styles: { fontSize: 8, cellPadding: 5 }
  });

  finalizeAndSavePdf(doc, 'YouthTransformers_SocialMedia_Report.pdf', currentUser, 'Social Media Director', 'Livia Kirezi');

  await logActivity({
    actorUid: currentUser.uid,
    actorName: currentUser.displayName,
    actorRole: currentUser.role,
    action: 'Official Department PDF Generated',
    module: 'social_media',
    resourceType: 'pdf',
    resourceId: verId,
    details: `Generated Social Media PDF with ${posts.length} published gospel posts`,
    result: 'success'
  });
}

// 5. PROJECT & EQUIPMENT REPORT PDF
export async function downloadProjectReportPDF(currentUser: UserProfile): Promise<void> {
  const isAuthorized = currentUser.role === 'projects_manager' || currentUser.role === 'leader';
  if (!isAuthorized) {
    await logActivity({
      actorUid: currentUser.uid,
      actorName: currentUser.displayName,
      actorRole: currentUser.role,
      action: 'Unauthorized PDF Download Rejected',
      module: 'projects',
      resourceType: 'pdf',
      resourceId: 'rep_projects',
      details: `Denied Projects PDF download to ${currentUser.displayName} (${currentUser.role})`,
      result: 'denied'
    });
    throw new Error('Access Denied: You do not have permission to download Project & Equipment reports.');
  }

  const projs = await getProjects();
  const eq = await getEquipment();
  const verId = `YT-PRJ-${Date.now().toString(36).toUpperCase()}`;
  const { doc, margin, pageWidth } = createPdfBase('Projects & Capital Asset Stewardship Report', 'Projects & Equipment Department Report', 'Projects & Equipment Maintenance', verId, currentUser);

  let y = (doc as any).lastAutoTable.finalY + 15;
  doc.setFillColor(241, 245, 249);
  doc.roundedRect(margin, y, pageWidth - margin * 2, 36, 6, 6, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor(71, 85, 105);
  doc.text(`Active Infrastructure Projects: ${projs.length}`, margin + 15, y + 22);
  doc.text(`Equipment Assets in Registry: ${eq.length}`, margin + 205, y + 22);
  doc.text(`Operational Condition: ${eq.filter(e => e.condition === 'Good' || e.condition === 'Excellent').length}`, margin + 375, y + 22);

  const projTable = projs.map(p => [
    p.name,
    p.leader,
    `${p.budget.toLocaleString()} RWF`,
    `${(p.currentSpending ?? 0).toLocaleString()} RWF`,
    `${p.progressPercent ?? p.progressPercentage ?? 0}%`,
    p.status.toUpperCase()
  ]);

  autoTable(doc, {
    startY: y + 46,
    head: [['Project Name', 'Project Lead', 'Budget', 'Spent', 'Progress', 'Status']],
    body: projTable,
    margin: { left: margin, right: margin },
    theme: 'striped',
    headStyles: { fillColor: [11, 93, 59], textColor: [255, 255, 255], fontStyle: 'bold', fontSize: 8 },
    styles: { fontSize: 8, cellPadding: 5 }
  });

  const eqTable = eq.map(e => [
    e.name,
    e.category,
    e.assetTag || 'N/A',
    e.condition.toUpperCase(),
    e.responsiblePerson || 'Ministry Storage'
  ]);

  autoTable(doc, {
    startY: (doc as any).lastAutoTable.finalY + 16,
    head: [['Equipment Asset Name', 'Category', 'Serial / Tag', 'Physical Condition', 'Custodian / Location']],
    body: eqTable,
    margin: { left: margin, right: margin },
    theme: 'striped',
    headStyles: { fillColor: [212, 167, 44], textColor: [30, 41, 59], fontStyle: 'bold', fontSize: 8 },
    styles: { fontSize: 8, cellPadding: 5 }
  });

  finalizeAndSavePdf(doc, 'YouthTransformers_Projects_Report.pdf', currentUser, 'Projects Manager', 'Rene Cyubahiro');

  await logActivity({
    actorUid: currentUser.uid,
    actorName: currentUser.displayName,
    actorRole: currentUser.role,
    action: 'Official Department PDF Generated',
    module: 'projects',
    resourceType: 'pdf',
    resourceId: verId,
    details: `Generated Projects & Equipment PDF with ${projs.length} projects and ${eq.length} assets`,
    result: 'success'
  });
}

// 6. ATTENDANCE REPORT PDF
export async function downloadAttendanceReportPDF(currentUser: UserProfile): Promise<void> {
  const isAuthorized = ['bible_study', 'level1_leader', 'leader'].includes(currentUser.role);
  if (!isAuthorized) {
    await logActivity({
      actorUid: currentUser.uid,
      actorName: currentUser.displayName,
      actorRole: currentUser.role,
      action: 'Unauthorized PDF Download Rejected',
      module: 'attendance',
      resourceType: 'pdf',
      resourceId: 'rep_attendance',
      details: `Denied Attendance PDF download to ${currentUser.displayName} (${currentUser.role})`,
      result: 'denied'
    });
    throw new Error('Access Denied: You do not have permission to download Attendance reports.');
  }

  const records = await getAttendance();
  const members = await getMembers();
  const verId = `YT-ATT-${Date.now().toString(36).toUpperCase()}`;
  const { doc, margin, pageWidth } = createPdfBase('Ministry Fellowship & Discipleship Attendance Audit', 'Attendance & Participation Report', 'Discipleship & Attendance Oversight', verId, currentUser);

  let y = (doc as any).lastAutoTable.finalY + 15;
  doc.setFillColor(241, 245, 249);
  doc.roundedRect(margin, y, pageWidth - margin * 2, 36, 6, 6, 'F');
  const presentCount = records.filter(r => r.status === 'present').length;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor(71, 85, 105);
  doc.text(`Enrolled Disciples: ${members.length}`, margin + 15, y + 22);
  doc.text(`Total Attendance Records: ${records.length}`, margin + 180, y + 22);
  doc.text(`Present Check-ins: ${presentCount} (${records.length ? Math.round((presentCount / records.length) * 100) : 0}%)`, margin + 355, y + 22);

  const tableData = records.map(r => [
    r.dateStr,
    r.eventName,
    r.memberName,
    r.eventType,
    r.status.toUpperCase(),
    r.recordedBy
  ]);

  autoTable(doc, {
    startY: y + 46,
    head: [['Date', 'Gathering / Service', 'Member Name', 'Event Type', 'Status', 'Audited By']],
    body: tableData,
    margin: { left: margin, right: margin },
    theme: 'striped',
    headStyles: { fillColor: [11, 93, 59], textColor: [255, 255, 255], fontStyle: 'bold', fontSize: 8 },
    styles: { fontSize: 8, cellPadding: 5 }
  });

  finalizeAndSavePdf(doc, 'YouthTransformers_Attendance_Report.pdf', currentUser, 'Discipleship Attendance Lead', currentUser.displayName);

  await logActivity({
    actorUid: currentUser.uid,
    actorName: currentUser.displayName,
    actorRole: currentUser.role,
    action: 'Official Department PDF Generated',
    module: 'attendance',
    resourceType: 'pdf',
    resourceId: verId,
    details: `Generated Attendance PDF with ${records.length} recorded service gatherings`,
    result: 'success'
  });
}

// 7. COMMITTEE REPORT PDF
export async function downloadCommitteeReportPDF(currentUser: UserProfile): Promise<void> {
  const isAuthorized = currentUser.role === 'committee_coordinator' || currentUser.role === 'leader';
  if (!isAuthorized) {
    await logActivity({
      actorUid: currentUser.uid,
      actorName: currentUser.displayName,
      actorRole: currentUser.role,
      action: 'Unauthorized PDF Download Rejected',
      module: 'committee',
      resourceType: 'pdf',
      resourceId: 'rep_committee',
      details: `Denied Committee PDF download to ${currentUser.displayName} (${currentUser.role})`,
      result: 'denied'
    });
    throw new Error('Access Denied: You do not have permission to download Committee reports.');
  }

  const tasks = await getCommitteeTasks();
  const reports = await getReports();
  const verId = `YT-COM-${Date.now().toString(36).toUpperCase()}`;
  const { doc, margin, pageWidth } = createPdfBase('Executive Committee Governance & Deliverables Report', 'Executive Committee Report', 'Committee Coordination & Deliverables', verId, currentUser);

  let y = (doc as any).lastAutoTable.finalY + 15;
  doc.setFillColor(241, 245, 249);
  doc.roundedRect(margin, y, pageWidth - margin * 2, 36, 6, 6, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor(71, 85, 105);
  doc.text(`Total Assigned Tasks: ${tasks.length}`, margin + 15, y + 22);
  doc.text(`Completed Deliverables: ${tasks.filter(t => t.status === 'completed' || t.status === 'approved').length}`, margin + 180, y + 22);
  doc.text(`Submitted Ministry Reports: ${reports.length}`, margin + 355, y + 22);

  const tableData = tasks.map(t => [
    t.title,
    t.assignedToName,
    t.department,
    t.priority?.toUpperCase() || 'MEDIUM',
    t.dueDate,
    t.status.replace('_', ' ').toUpperCase()
  ]);

  autoTable(doc, {
    startY: y + 46,
    head: [['Action Item / Deliverable', 'Assigned Leader', 'Department', 'Priority', 'Due Date', 'Status']],
    body: tableData,
    margin: { left: margin, right: margin },
    theme: 'striped',
    headStyles: { fillColor: [11, 93, 59], textColor: [255, 255, 255], fontStyle: 'bold', fontSize: 8 },
    styles: { fontSize: 8, cellPadding: 5 }
  });

  finalizeAndSavePdf(doc, 'YouthTransformers_Committee_Report.pdf', currentUser, 'Committee Coordinator', 'Green London');

  await logActivity({
    actorUid: currentUser.uid,
    actorName: currentUser.displayName,
    actorRole: currentUser.role,
    action: 'Official Department PDF Generated',
    module: 'committee',
    resourceType: 'pdf',
    resourceId: verId,
    details: `Generated Committee PDF with ${tasks.length} action items`,
    result: 'success'
  });
}
