import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { CommitteeReport, UserProfile } from '../types';
import { logActivity } from './activityLogService';

export interface GeneratePDFOptions {
  report: CommitteeReport;
  generatedBy: string;
  totalMembers?: number;
  activeMembers?: number;
  treasuryBalance?: number;
  activeProjects?: number;
}

export async function generateOfficialMinistryPDF(options: GeneratePDFOptions): Promise<void> {
  const { report, generatedBy, totalMembers, activeMembers, treasuryBalance, activeProjects } = options;

  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'pt',
    format: 'a4'
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 40;

  // Header Deep Green Banner
  doc.setFillColor(11, 93, 59); // #0B5D3B Deep Green
  doc.rect(0, 0, pageWidth, 85, 'F');

  // Gold accent bar
  doc.setFillColor(212, 167, 44); // #D4A72C Gold
  doc.rect(0, 85, pageWidth, 6, 'F');

  // Title text
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.text('YOUTH TRANSFORMERS MINISTRY', margin, 36);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  doc.setTextColor(254, 243, 199); // light gold
  doc.text('LEADER LEO BENIE HATEGEKA • EXECUTIVE MINISTRY REPORT', margin, 54);
  doc.setFontSize(9);
  doc.setTextColor(209, 250, 229);
  doc.text(`Official Document Verification ID: YT-${Date.now().toString(36).toUpperCase()}`, margin, 70);

  // Metadata Table
  let y = 112;
  doc.setTextColor(31, 41, 55);
  doc.setFontSize(10);

  const reportTitle = report.title || `${report.department} Progress Report`;
  const submitter = report.submittedByName || report.authorName || 'Ministry Executive';

  const metaData = [
    ['REPORT TITLE:', reportTitle, 'STATUS:', (report.status || 'SUBMITTED').toUpperCase()],
    ['DEPARTMENT:', report.department || 'Executive Leadership', 'REPORTING PERIOD:', report.reportingPeriod || 'Current Term'],
    ['SUBMITTED BY:', submitter, 'GENERATED BY:', generatedBy],
    ['DATE SUBMITTED:', report.dateSubmitted || report.dateStr || new Date().toISOString().split('T')[0], 'SECURITY LEVEL:', 'Protected Ministry Record']
  ];

  autoTable(doc, {
    startY: y,
    theme: 'grid',
    head: [],
    body: metaData,
    margin: { left: margin, right: margin },
    styles: {
      fontSize: 9,
      cellPadding: 5,
      textColor: [31, 41, 55]
    },
    columnStyles: {
      0: { fontStyle: 'bold', fillColor: [248, 250, 252], cellWidth: 120 },
      1: { cellWidth: 160 },
      2: { fontStyle: 'bold', fillColor: [248, 250, 252], cellWidth: 110 },
      3: { fontStyle: 'bold', textColor: [11, 93, 59] }
    }
  });

  // Calculate start position after table
  const lastTable = (doc as any).lastAutoTable;
  y = lastTable ? lastTable.finalY + 20 : y + 90;

  // Key Metrics Card Row if available
  if (totalMembers !== undefined || treasuryBalance !== undefined) {
    doc.setFillColor(241, 245, 249);
    doc.roundedRect(margin, y, pageWidth - margin * 2, 40, 6, 6, 'F');
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.setTextColor(71, 85, 105);

    const activeM = activeMembers ?? totalMembers ?? 0;
    const balanceStr = (treasuryBalance ?? 0).toLocaleString() + ' RWF';
    const projCount = activeProjects ?? 0;

    doc.text(`Active Members: ${activeM}`, margin + 14, y + 24);
    doc.text(`Treasury Balance: ${balanceStr}`, margin + 170, y + 24);
    doc.text(`Active Projects: ${projCount}`, margin + 360, y + 24);

    y += 54;
  }

  // Core Sections
  const execSummary = report.executiveSummary || report.accomplished || 'Comprehensive departmental activities conducted in line with Youth Transformers spiritual mandate.';
  const activities = report.activitiesCompleted || report.currentWork || 'Weekly fellowships, prayer meetings, and member outreach completed successfully.';
  const challenges = report.challenges || 'No critical bottlenecks reported during this period.';
  const nextSteps = report.nextSteps || 'Proceed with planned discipleship curriculum and campus evangelism missions.';

  const sections = [
    { title: '1. Executive Summary & Overview', content: execSummary },
    { title: '2. Activities & Deliverables Completed', content: activities },
    { title: '3. Challenges & Operational Bottlenecks', content: challenges },
    { title: '4. Strategic Next Steps & Pastoral Recommendations', content: nextSteps }
  ];

  sections.forEach((sec) => {
    if (y > 720) {
      doc.addPage();
      y = 50;
    }

    // Section title container
    doc.setFillColor(236, 253, 245); // light green container
    doc.rect(margin, y, pageWidth - margin * 2, 20, 'F');
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(11, 93, 59); // deep green
    doc.text(sec.title, margin + 8, y + 14);
    y += 26;

    // Section body
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9.5);
    doc.setTextColor(55, 65, 81);

    const splitLines = doc.splitTextToSize(sec.content || 'None reported.', pageWidth - margin * 2 - 16);
    doc.text(splitLines, margin + 8, y);
    y += splitLines.length * 13 + 18;
  });

  // Verification & Signature Section
  if (y > 680) {
    doc.addPage();
    y = 50;
  }

  y += 10;
  doc.setDrawColor(203, 213, 225);
  doc.line(margin, y, pageWidth - margin, y);
  y += 30;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor(30, 41, 59);
  doc.text('VERIFIED BY DEPARTMENT COORDINATION:', margin, y);
  doc.text('APPROVED BY MINISTRY LEADER:', margin + 270, y);

  y += 35;
  doc.line(margin, y, margin + 200, y);
  doc.line(margin + 270, y, margin + 470, y);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.text(`${submitter} • Authorized Submitter`, margin, y + 12);
  doc.text('Leader Leo Benie Hategeka • Youth Transformers', margin + 270, y + 12);

  // Footer on all pages
  const totalPages = (doc.internal as any).getNumberOfPages();
  const dateNow = new Date().toLocaleString();

  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setDrawColor(226, 232, 240);
    doc.line(margin, 800, pageWidth - margin, 800);

    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 116, 139);
    doc.text(
      `Generated by ${generatedBy} on ${dateNow} • Youth Transformers Ministry Management Portal`,
      margin,
      814
    );
    doc.text(`Page ${i} of ${totalPages}`, pageWidth - margin - 50, 814);
  }

  const cleanPeriod = (report.reportingPeriod || 'report').replace(/[^a-zA-Z0-9_-]/g, '_');
  const filename = `YouthTransformers_${cleanPeriod}_Official_Report.pdf`;

  doc.save(filename);
}

export async function generateAndDownloadReportPdf(
  report: CommitteeReport,
  currentUser: UserProfile
): Promise<void> {
  return generateOfficialMinistryPDF({
    report,
    generatedBy: `${currentUser.displayName} (${currentUser.role})`
  });
}
